---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "docker :whale:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
<<<<<<< HEAD
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "github-actions :octocat:"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "javascript :coffee:"
=======
      interval: "weekly"
    # ignore:
    #   # Managed by cisagov/skeleton-generic
    #   - dependency-name: actions/cache
    #   - dependency-name: actions/checkout
    #   - dependency-name: actions/setup-go
    #   - dependency-name: actions/setup-python
    #   - dependency-name: hashicorp/setup-terraform
    #   - dependency-name: mxschmitt/action-tmate
>>>>>>> e803e1ac48ea53dc766d05935fbc38d2f4ad385e

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "python :snake:"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "terraform :earth_americas:"
