---
name: Deploy to AWS

on:
  push:
    branches:
      - develop
      - production
      - staging

env:
  ALL_ENVS_CAN_SEE: ${{ vars.ALL_ENVS_CAN_SEE }}
  AWS_REGION: us-east-1  # TODO: Make this a variable
  DEPLOY_TF_BACKEND_ROLE_ARN: ${{ vars.TF_BACKEND_ROLE_ARN }}
  DEPLOY_TF_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
  DEPLOY_TF_DYNAMODB: ${{ vars.TF_BACKEND_DYNAMODB }}
  DEPLOY_TF_VARS_URL: ${{ vars.TF_VARS_URL }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@8d1f141b985510f36a0376b75b4dc8b0cfc90e8a
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@158bbf4d6158a44a7e13f76295dc55a69e481a6e

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Print some things
        run: |
            echo "This is what is in the environment:"
            env | sort
